---
# tasks file for ubuntu_package
- name: Add apt key
  apt_key:
    url: "{{ url }}"
    state: present
  when: url != ""

- name: add repository
  apt_repository:
    repo: "{{ repo }}"
    filename: "{{ filename }}"
    state: present
  when: repo != ""

- name: Install package
  apt:
    name: "{{ package }}"
    state: latest
    
- name: start and enable
  service:
    name: "{{ service }}"
    state: started
    enabled: yes
  when: service != ""
